# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      if VERSION >= v"0.7.0-DEV.5183" && (isfile("Project.toml") || isfile("JuliaProject.toml"))
          Pkg.add("Colors")
          Pkg.build()
          Pkg.test(coverage=true)
      else
          Pkg.clone(pwd())
          Pkg.add("Colors")
          Pkg.build("Luxor")
          Pkg.test("Luxor"; coverage=true)
      end'

after_success:
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Luxor"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())
      Pkg.add("Documenter")
      cd(Pkg.dir("Luxor"))
      include("docs/make.jl")'
