# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
env:
  global:
    - DOCUMENTER_DEBUG=true
after_success:
  - julia -e 'import Pkg; Pkg.add("Colors"); Pkg.build("Colors")'
  - julia -e 'import Pkg; Pkg.add("Luxor");  Pkg.build("Luxor")'
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import Luxor; include("docs/make.jl")'
  - julia -e 'import Pkg; cd(Pkg.dir("Luxor")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
