# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: 0.7
    - julia: nightly

notifications:
  email: false

before_script:
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'using Pkg; Pkg.add("Colors")'
  - julia -e 'using Pkg; Pkg.add("Luxor")'

script:
  - julia -e 'import Pkg; Pkg.test("Luxor"; coverage=true)'

after_success:
  - test $TRAVIS_OS_NAME = "linux" && julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - test $TRAVIS_OS_NAME = "osx" && julia -e 'using Coverage; Codecov.submit(process_folder())'
