# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.add("Colors")'
  - julia -e 'using Pkg; Pkg.add("Luxor")'
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'import Pkg; Pkg.test("Luxor"; coverage=true)'

jobs:
  include:
    - stage: deploy
      julia: 0.7
      os: osx
      script:
        - julia -e 'Pkg.add("Documenter")'
        - julia -e 'cd(Pkg.dir("Luxor")); include("docs/make.jl")'

after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("Luxor")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'; fi
